name: "Generate user report"
description: "Create a temporary user report under docs/User-Reports"
labels: ["user-report"]
body:
  - type: input
    id: name
    attributes:
      label: Player name
      placeholder: e.g. Test User
    validations:
      required: true
  - type: input
    id: account
    attributes:
      label: Account ID
      placeholder: 123456789
    validations:
      required: true
  - type: input
    id: rangedays
    attributes:
      label: Range (days)
      placeholder: 30
    validations:
      required: true
